steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      # Correctly points to the Asian multi-regional GCR
      - 'asia.gcr.io/${PROJECT_ID}/${_SERVICE_NAME}:$COMMIT_SHA'
      - '.'

  # Push the container image to the Asian multi-regional GCR
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'asia.gcr.io/${PROJECT_ID}/${_SERVICE_NAME}:$COMMIT_SHA'

  # Deploy container image to a specific region in Asia
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image'
      - 'asia.gcr.io/${PROJECT_ID}/${_SERVICE_NAME}:$COMMIT_SHA'
      # --- THIS IS THE KEY ---
      # Deploy the service to a specific, fast region in Asia
      - '--region'
      - '${_DEPLOY_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

images:
  - 'asia.gcr.io/${PROJECT_ID}/${_SERVICE_NAME}:$COMMIT_SHA'

substitutions:
  _SERVICE_NAME: 'pharmacy-api-service'
  # --- CORRECTED ---
  # We now specify a DEPLOY region. asia-southeast1 (Singapore) is a great choice.
  _DEPLOY_REGION: 'asia-southeast1'

options:
  logging: CLOUD_LOGGING_ONLY
