// // generate-styles.ts
// import * as fs from 'fs';
// import * as path from 'path';

// function findStylesPath(): string {
//   const relativePath = path.resolve('./node_modules/@dicebear/styles/dist');
//   if (fs.existsSync(relativePath)) return relativePath;

//   try {
//     const pkgPath = require.resolve('@dicebear/styles/package.json');
//     const distPath = path.join(path.dirname(pkgPath), 'dist');
//     if (fs.existsSync(distPath)) return distPath;
//     return path.dirname(pkgPath);
//   } catch {
//     console.error('❌ Could not locate @dicebear/styles in node_modules.');
//     process.exit(1);
//   }
// }

// const stylesPath = findStylesPath();
// const files = fs
//   .readdirSync(stylesPath)
//   .filter((file) => file.endsWith('.json') && file !== 'package.json');

// let importStatements = '';
// let mapObjectKeys = '';

// files.forEach((file) => {
//   const styleName = file.replace(/\.min\.json$/, '').replace(/\.json$/, '');
//   const camelCaseName = styleName.replace(/-([a-z])/g, (g) =>
//     g[1].toUpperCase(),
//   );

//   importStatements += `import ${camelCaseName} from '@dicebear/styles/dist/${file}';\n`;

//   // FIX: If the string name has a hyphen (like 'pixel-art'), keep the key-value pair.
//   // If it's a single word matching the variable (like 'bottts'), use clean shorthand syntax!
//   if (styleName === camelCaseName) {
//     mapObjectKeys += `  ${camelCaseName},\n`;
//   } else {
//     mapObjectKeys += `  '${styleName}': ${camelCaseName},\n`;
//   }
// });

// const fileContent = `// Automatically generated by generate-styles.ts
// ${importStatements}
// export const allStyles: Record<string, any> = {
// ${mapObjectKeys}};
// `;

// const outputPath = path.resolve('./src/dicebear-styles.map.ts');
// fs.mkdirSync(path.dirname(outputPath), { recursive: true });
// fs.writeFileSync(outputPath, fileContent);

// console.log(`✅ Successfully generated lint-safe shorthand map file.`);
