// generate-dicebear.ts
import fs from 'node:fs';
import path from 'node:path';

// Target the physical node_modules path directory layout directly
const rootDir = process.cwd();
const stylesDir = path.join(
  rootDir,
  'node_modules',
  '@dicebear',
  'styles',
  'dist',
);

console.log(`🔍 Reading DiceBear styles from: ${stylesDir}`);

if (!fs.existsSync(stylesDir)) {
  console.error(
    `❌ Path does not exist! Could not locate directory: ${stylesDir}`,
  );
  console.error('Make sure you have run "npm install @dicebear/styles" first.');
  process.exit(1);
}

const styles: Record<string, unknown> = {};
const files = fs.readdirSync(stylesDir);

for (const file of files) {
  // Read the minified JSON distributions directly from disk
  if (!file.endsWith('.min.json')) continue;

  // Clean the file suffix to get a pretty key name (e.g., "bottts")
  const styleName = file.replace('.min.json', '');

  styles[styleName] = JSON.parse(
    fs.readFileSync(path.join(stylesDir, file), 'utf8'),
  );
}

const totalStyles = Object.keys(styles).length;
console.log(`Found ${totalStyles} style definitions.`);

// Generate the key-value text pairs statically right here in Node
const enumFields = Object.keys(styles)
  .map((name) => {
    // Converts kebab-case like 'adventurer-neutral' to PascalCase 'AdventurerNeutral'
    const pascalKey = name.replace(/(^\b|-)([a-z])/g, (_, __, letter) =>
      letter.toUpperCase(),
    );
    return `  ${pascalKey}: '${name}',`;
  })
  .join('\n');

// 1. Stringify the object layout first
const rawJson = JSON.stringify(styles, null, 2);

// 2. Format double quotes to single quotes safely for JS/TS object declaration context
// - Swaps out outer property keys and standard strings wrapped in double quotes
// - Unescapes any internal escaped double quotes (\") back to standard double quotes inside strings
const singleQuoteJson = rawJson.replace(/"/g, "'").replace(/\\'/g, '"');

// NOTICE: We type-annotate the export as Record<string, unknown> up front!
// This explicitly blocks TS from trying to map out a massive inner tree
// during code generation, completely stopping the compiler length limits!
// Output a standard Record<string, unknown> template to completely block TS serialization bloat errors!
// const output = `// Auto-generated by generate-dicebear.ts. Do not edit.

// // Explicit type annotation prevents TS from trying to serialize the massive inline schemas
// export const allStyles: Record<string, unknown> = ${singleQuoteJson};
// `;

// const output = `// Auto-generated by generate-dicebear.ts. Do not edit.

// export const allStyles: Record<string, unknown> = ${singleQuoteJson};

// // Single source of truth for runtime route checks
// export const availableStyleNames = ${JSON.stringify(Object.keys(styles))} as const;

// export type DiceBearStyle = typeof availableStyleNames[number];
// `;

const output = `// Auto-generated by generate-dicebear.ts. Do not edit.

export const allStyles: Record<string, unknown> = ${singleQuoteJson};

/* --- Single source of truth for runtime route checks --- */
// 1. Read-only tuple array for runtime validation checks
export const availableStyleNames = ${JSON.stringify(Object.keys(styles))} as const;

// 2. Statically generated to prevent regex-escaping runtime bugs in template strings
export const DiceBearStyle = {
${enumFields}
} as const;

// // 2. Automated pseudo-enum object replacement
// export const DiceBearStyle = Object.fromEntries(
//   availableStyleNames.map(name => [
//     // Converts kebab-case names like 'adventurer-neutral' to PascalCase 'AdventurerNeutral'
//     name.replace(/(^\\|-)([a-z])/g, (_, __, letter) => letter.toUpperCase()), 
//     name
//   ])
// ) as { [K in typeof availableStyleNames[number] as ReplaceKebab<K>]: K };

// // Type helper to construct exact PascalCase structural map keys automatically
// type ReplaceKebab<S extends string> = S extends \`\${infer T}-\${infer U}\`
//   ? \`\${Capitalize<T>}\${ReplaceKebab<U>}\`
//   : Capitalize<S>;

// 3. Union string type definition (e.g., 'adventurer' | 'bottts' | ...)
export type DiceBearStyleType = typeof availableStyleNames[number];
`;

// // Ensure output folder tree exists
const outputPath = path.join(rootDir, 'src', 'dicebear-styles.map.ts');
fs.mkdirSync(path.dirname(outputPath), { recursive: true });
fs.writeFileSync(outputPath, output);

console.log(
  `✅ Generated optimal, up-to-date ${Object.keys(files).length} DiceBear styles in: ${outputPath}`,
);

// const pkgPath = require.resolve('@dicebear/styles/package.json');
// const stylesDir = path.join(path.dirname(pkgPath), 'src');

// for (const file of fs.readdirSync(stylesDir)) {
//   // Target the minified distribution styles
//   if (!file.endsWith('.min.json')) continue;

//   // Clean the file suffix to get a pretty key name (e.g., "bottts")
//   const styleName = file.replace('.min.json', '');

//   styles[styleName] = JSON.parse(
//     fs.readFileSync(path.join(stylesDir, file), 'utf8'),
//   );
// }

// // 2. Output the exact map using string templates
// // const output = `
// // // Auto-generated. Do not edit.

// // export const allStyles = ${JSON.stringify(styles, null, 2)} as const;
// // `;

// const output = `// Auto-generated by generate-dicebear.ts. Do not edit.

// // Explicit type annotation prevents TS from trying to serialize the massive inline schemas
// export const allStyles: Record<string, unknown> = ${JSON.stringify(styles, null, 2)};
// `;

// // Ensure output folder tree exists
// const outputPath = path.resolve('./src/dicebear-styles.map.ts');
// fs.mkdirSync(path.dirname(outputPath), { recursive: true });
// fs.writeFileSync(outputPath, output);

// // fs.writeFileSync(path.resolve('./src/dicebear-styles.map.ts'), output);

// // console.log(`Generated ${Object.keys(styles).length} DiceBear styles`);
// console.log(
//   `✅ Generated ${Object.keys(styles).length} DiceBear styles in: ${outputPath}`,
// );
