// Automatically generated by generate-styles.ts
import adventurerNeutral from '@dicebear/styles/dist/adventurer-neutral.min.json';
import adventurer from '@dicebear/styles/dist/adventurer.min.json';
import avataaarsNeutral from '@dicebear/styles/dist/avataaars-neutral.min.json';
import avataaars from '@dicebear/styles/dist/avataaars.min.json';
import bigEarsNeutral from '@dicebear/styles/dist/big-ears-neutral.min.json';
import bigEars from '@dicebear/styles/dist/big-ears.min.json';
import bigSmile from '@dicebear/styles/dist/big-smile.min.json';
import botttsNeutral from '@dicebear/styles/dist/bottts-neutral.min.json';
import bottts from '@dicebear/styles/dist/bottts.min.json';
import croodlesNeutral from '@dicebear/styles/dist/croodles-neutral.min.json';
import croodles from '@dicebear/styles/dist/croodles.min.json';
import disco from '@dicebear/styles/dist/disco.min.json';
import dylan from '@dicebear/styles/dist/dylan.min.json';
import funEmoji from '@dicebear/styles/dist/fun-emoji.min.json';
import glass from '@dicebear/styles/dist/glass.min.json';
import glyphs from '@dicebear/styles/dist/glyphs.min.json';
import icons from '@dicebear/styles/dist/icons.min.json';
import identicon from '@dicebear/styles/dist/identicon.min.json';
import initialFace from '@dicebear/styles/dist/initial-face.min.json';
import initials from '@dicebear/styles/dist/initials.min.json';
import loreleiNeutral from '@dicebear/styles/dist/lorelei-neutral.min.json';
import lorelei from '@dicebear/styles/dist/lorelei.min.json';
import micah from '@dicebear/styles/dist/micah.min.json';
import miniavs from '@dicebear/styles/dist/miniavs.min.json';
import notionistsNeutral from '@dicebear/styles/dist/notionists-neutral.min.json';
import notionists from '@dicebear/styles/dist/notionists.min.json';
import openPeeps from '@dicebear/styles/dist/open-peeps.min.json';
import personas from '@dicebear/styles/dist/personas.min.json';
import pixelArtNeutral from '@dicebear/styles/dist/pixel-art-neutral.min.json';
import pixelArt from '@dicebear/styles/dist/pixel-art.min.json';
import rings from '@dicebear/styles/dist/rings.min.json';
import shapeGrid from '@dicebear/styles/dist/shape-grid.min.json';
import shapes from '@dicebear/styles/dist/shapes.min.json';
import stripes from '@dicebear/styles/dist/stripes.min.json';
import thumbs from '@dicebear/styles/dist/thumbs.min.json';
import toonHead from '@dicebear/styles/dist/toon-head.min.json';
import triangles from '@dicebear/styles/dist/triangles.min.json';

export const allStyles: Record<string, any> = {
  'adventurer-neutral': adventurerNeutral,
  adventurer,
  'avataaars-neutral': avataaarsNeutral,
  avataaars,
  'big-ears-neutral': bigEarsNeutral,
  'big-ears': bigEars,
  'big-smile': bigSmile,
  'bottts-neutral': botttsNeutral,
  bottts,
  'croodles-neutral': croodlesNeutral,
  croodles,
  disco,
  dylan,
  'fun-emoji': funEmoji,
  glass,
  glyphs,
  icons,
  identicon,
  'initial-face': initialFace,
  initials,
  'lorelei-neutral': loreleiNeutral,
  lorelei,
  micah,
  miniavs,
  'notionists-neutral': notionistsNeutral,
  notionists,
  'open-peeps': openPeeps,
  personas,
  'pixel-art-neutral': pixelArtNeutral,
  'pixel-art': pixelArt,
  rings,
  'shape-grid': shapeGrid,
  shapes,
  stripes,
  thumbs,
  'toon-head': toonHead,
  triangles,
};
